### PR TITLE
chore: add asf yaml

### PR DESCRIPTION
**Pull request by chunshao90**
## Rationale
Add `.asf.yaml`.

## Test Plan
No need.

### CODE REVIEW

**Comment by caicancai** [comment]
I think we should add a cli check for icense. I don’t know if horaedb currently has this measure.

**Comment by chunshao90** [comment]
> I think we should add a cli check for icense. I don’t know if horaedb currently has this measure.

license checker？

**Comment by caicancai** [comment]
> > I think we should add a cli check for icense. I don’t know if horaedb currently has this measure.
> 
> license checker？

yes

**Review by tanruixiang — APPROVED** [review]
LGTM

**Comment by chunshao90** [comment]
> I think we should add a cli check for icense. I don’t know if horaedb currently has this measure.

License checker already exists in horaemeta.

**Pull request merged**
